/**
 * @fileoverview gRPC-Web generated client stub for extension
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.1.1
// 	protoc              v7.36.2
// source: extension/extension_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var extension_extension_pb = require('../extension/extension_pb.js')

var v2_hcommon_common_pb = require('../v2/hcommon/common_pb.js')
const proto = {};
proto.extension = require('./extension_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.extension.ExtensionHostServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.extension.ExtensionHostServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.extension.ExtensionList>}
 */
const methodDescriptor_ExtensionHostService_ListExtensions = new grpc.web.MethodDescriptor(
  '/extension.ExtensionHostService/ListExtensions',
  grpc.web.MethodType.UNARY,
  v2_hcommon_common_pb.Empty,
  extension_extension_pb.ExtensionList,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  extension_extension_pb.ExtensionList.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.extension.ExtensionList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.extension.ExtensionList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.extension.ExtensionHostServiceClient.prototype.listExtensions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/extension.ExtensionHostService/ListExtensions',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_ListExtensions,
      callback);
};


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.extension.ExtensionList>}
 *     Promise that resolves to the response
 */
proto.extension.ExtensionHostServicePromiseClient.prototype.listExtensions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/extension.ExtensionHostService/ListExtensions',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_ListExtensions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.extension.ExtensionRequest,
 *   !proto.extension.ExtensionResponse>}
 */
const methodDescriptor_ExtensionHostService_Connect = new grpc.web.MethodDescriptor(
  '/extension.ExtensionHostService/Connect',
  grpc.web.MethodType.SERVER_STREAMING,
  extension_extension_pb.ExtensionRequest,
  extension_extension_pb.ExtensionResponse,
  /**
   * @param {!proto.extension.ExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  extension_extension_pb.ExtensionResponse.deserializeBinary
);


/**
 * @param {!proto.extension.ExtensionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.extension.ExtensionResponse>}
 *     The XHR Node Readable Stream
 */
proto.extension.ExtensionHostServiceClient.prototype.connect =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/extension.ExtensionHostService/Connect',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Connect);
};


/**
 * @param {!proto.extension.ExtensionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.extension.ExtensionResponse>}
 *     The XHR Node Readable Stream
 */
proto.extension.ExtensionHostServicePromiseClient.prototype.connect =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/extension.ExtensionHostService/Connect',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Connect);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.extension.EditExtensionRequest,
 *   !proto.extension.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_EditExtension = new grpc.web.MethodDescriptor(
  '/extension.ExtensionHostService/EditExtension',
  grpc.web.MethodType.UNARY,
  extension_extension_pb.EditExtensionRequest,
  extension_extension_pb.ExtensionActionResult,
  /**
   * @param {!proto.extension.EditExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  extension_extension_pb.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.extension.EditExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.extension.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.extension.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.extension.ExtensionHostServiceClient.prototype.editExtension =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/extension.ExtensionHostService/EditExtension',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_EditExtension,
      callback);
};


/**
 * @param {!proto.extension.EditExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.extension.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.extension.ExtensionHostServicePromiseClient.prototype.editExtension =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/extension.ExtensionHostService/EditExtension',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_EditExtension);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.extension.SendExtensionDataRequest,
 *   !proto.extension.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_SubmitForm = new grpc.web.MethodDescriptor(
  '/extension.ExtensionHostService/SubmitForm',
  grpc.web.MethodType.UNARY,
  extension_extension_pb.SendExtensionDataRequest,
  extension_extension_pb.ExtensionActionResult,
  /**
   * @param {!proto.extension.SendExtensionDataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  extension_extension_pb.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.extension.SendExtensionDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.extension.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.extension.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.extension.ExtensionHostServiceClient.prototype.submitForm =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/extension.ExtensionHostService/SubmitForm',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_SubmitForm,
      callback);
};


/**
 * @param {!proto.extension.SendExtensionDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.extension.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.extension.ExtensionHostServicePromiseClient.prototype.submitForm =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/extension.ExtensionHostService/SubmitForm',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_SubmitForm);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.extension.ExtensionRequest,
 *   !proto.extension.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_Close = new grpc.web.MethodDescriptor(
  '/extension.ExtensionHostService/Close',
  grpc.web.MethodType.UNARY,
  extension_extension_pb.ExtensionRequest,
  extension_extension_pb.ExtensionActionResult,
  /**
   * @param {!proto.extension.ExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  extension_extension_pb.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.extension.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.extension.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.extension.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.extension.ExtensionHostServiceClient.prototype.close =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/extension.ExtensionHostService/Close',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Close,
      callback);
};


/**
 * @param {!proto.extension.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.extension.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.extension.ExtensionHostServicePromiseClient.prototype.close =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/extension.ExtensionHostService/Close',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Close);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.extension.ExtensionRequest,
 *   !proto.extension.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_GetUI = new grpc.web.MethodDescriptor(
  '/extension.ExtensionHostService/GetUI',
  grpc.web.MethodType.UNARY,
  extension_extension_pb.ExtensionRequest,
  extension_extension_pb.ExtensionActionResult,
  /**
   * @param {!proto.extension.ExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  extension_extension_pb.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.extension.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.extension.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.extension.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.extension.ExtensionHostServiceClient.prototype.getUI =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/extension.ExtensionHostService/GetUI',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_GetUI,
      callback);
};


/**
 * @param {!proto.extension.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.extension.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.extension.ExtensionHostServicePromiseClient.prototype.getUI =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/extension.ExtensionHostService/GetUI',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_GetUI);
};


module.exports = proto.extension;
