/**
 * @fileoverview gRPC-Web generated client stub for hcore
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v7.35.1
// source: v2/hcore/hcore_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var v2_hcommon_common_pb = require('../../v2/hcommon/common_pb.js')

var v2_hcore_hcore_pb = require('../../v2/hcore/hcore_pb.js')
const proto = {};
proto.hcore = require('./hcore_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hcore.CoreClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.hcore.CorePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.StartRequest,
 *   !proto.hcore.CoreInfoResponse>}
 */
const methodDescriptor_Core_Start = new grpc.web.MethodDescriptor(
  '/hcore.Core/Start',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.StartRequest,
  v2_hcore_hcore_pb.CoreInfoResponse,
  /**
   * @param {!proto.hcore.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/Start',
      request,
      metadata || {},
      methodDescriptor_Core_Start,
      callback);
};


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/Start',
      request,
      metadata || {},
      methodDescriptor_Core_Start);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.CoreInfoResponse>}
 */
const methodDescriptor_Core_CoreInfoListener = new grpc.web.MethodDescriptor(
  '/hcore.Core/CoreInfoListener',
  grpc.web.MethodType.SERVER_STREAMING,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.CoreInfoResponse,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.coreInfoListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/CoreInfoListener',
      request,
      metadata || {},
      methodDescriptor_Core_CoreInfoListener);
};


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CorePromiseClient.prototype.coreInfoListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/CoreInfoListener',
      request,
      metadata || {},
      methodDescriptor_Core_CoreInfoListener);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.OutboundGroupList>}
 */
const methodDescriptor_Core_OutboundsInfo = new grpc.web.MethodDescriptor(
  '/hcore.Core/OutboundsInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.OutboundGroupList,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.OutboundGroupList.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.outboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/OutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_OutboundsInfo);
};


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CorePromiseClient.prototype.outboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/OutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_OutboundsInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.OutboundGroupList>}
 */
const methodDescriptor_Core_MainOutboundsInfo = new grpc.web.MethodDescriptor(
  '/hcore.Core/MainOutboundsInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.OutboundGroupList,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.OutboundGroupList.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.mainOutboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/MainOutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_MainOutboundsInfo);
};


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CorePromiseClient.prototype.mainOutboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/MainOutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_MainOutboundsInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.SystemInfo>}
 */
const methodDescriptor_Core_GetSystemInfo = new grpc.web.MethodDescriptor(
  '/hcore.Core/GetSystemInfo',
  grpc.web.MethodType.UNARY,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.SystemInfo,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.SystemInfo.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.SystemInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.SystemInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.getSystemInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/GetSystemInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfo,
      callback);
};


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.SystemInfo>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.getSystemInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/GetSystemInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.SystemInfo>}
 */
const methodDescriptor_Core_GetSystemInfoStream = new grpc.web.MethodDescriptor(
  '/hcore.Core/GetSystemInfoStream',
  grpc.web.MethodType.SERVER_STREAMING,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.SystemInfo,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.SystemInfo.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.getSystemInfoStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/GetSystemInfoStream',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfoStream);
};


/**
 * @param {!proto.hcommon.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CorePromiseClient.prototype.getSystemInfoStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/GetSystemInfoStream',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfoStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.SetupRequest,
 *   !proto.hcommon.Response>}
 */
const methodDescriptor_Core_Setup = new grpc.web.MethodDescriptor(
  '/hcore.Core/Setup',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.SetupRequest,
  v2_hcommon_common_pb.Response,
  /**
   * @param {!proto.hcore.SetupRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcommon_common_pb.Response.deserializeBinary
);


/**
 * @param {!proto.hcore.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcommon.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcommon.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.setup =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/Setup',
      request,
      metadata || {},
      methodDescriptor_Core_Setup,
      callback);
};


/**
 * @param {!proto.hcore.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcommon.Response>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.setup =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/Setup',
      request,
      metadata || {},
      methodDescriptor_Core_Setup);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.ParseRequest,
 *   !proto.hcore.ParseResponse>}
 */
const methodDescriptor_Core_Parse = new grpc.web.MethodDescriptor(
  '/hcore.Core/Parse',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.ParseRequest,
  v2_hcore_hcore_pb.ParseResponse,
  /**
   * @param {!proto.hcore.ParseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.ParseResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.ParseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.ParseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.parse =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/Parse',
      request,
      metadata || {},
      methodDescriptor_Core_Parse,
      callback);
};


/**
 * @param {!proto.hcore.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.ParseResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.parse =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/Parse',
      request,
      metadata || {},
      methodDescriptor_Core_Parse);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.ChangeHiddifySettingsRequest,
 *   !proto.hcore.CoreInfoResponse>}
 */
const methodDescriptor_Core_ChangeHiddifySettings = new grpc.web.MethodDescriptor(
  '/hcore.Core/ChangeHiddifySettings',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.ChangeHiddifySettingsRequest,
  v2_hcore_hcore_pb.CoreInfoResponse,
  /**
   * @param {!proto.hcore.ChangeHiddifySettingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.ChangeHiddifySettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.changeHiddifySettings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/ChangeHiddifySettings',
      request,
      metadata || {},
      methodDescriptor_Core_ChangeHiddifySettings,
      callback);
};


/**
 * @param {!proto.hcore.ChangeHiddifySettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.changeHiddifySettings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/ChangeHiddifySettings',
      request,
      metadata || {},
      methodDescriptor_Core_ChangeHiddifySettings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.GenerateConfigRequest,
 *   !proto.hcore.GenerateConfigResponse>}
 */
const methodDescriptor_Core_GenerateConfig = new grpc.web.MethodDescriptor(
  '/hcore.Core/GenerateConfig',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.GenerateConfigRequest,
  v2_hcore_hcore_pb.GenerateConfigResponse,
  /**
   * @param {!proto.hcore.GenerateConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.GenerateConfigResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.GenerateConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.GenerateConfigResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.GenerateConfigResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.generateConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/GenerateConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateConfig,
      callback);
};


/**
 * @param {!proto.hcore.GenerateConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.GenerateConfigResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.generateConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/GenerateConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.StartRequest,
 *   !proto.hcore.CoreInfoResponse>}
 */
const methodDescriptor_Core_StartService = new grpc.web.MethodDescriptor(
  '/hcore.Core/StartService',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.StartRequest,
  v2_hcore_hcore_pb.CoreInfoResponse,
  /**
   * @param {!proto.hcore.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.startService =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/StartService',
      request,
      metadata || {},
      methodDescriptor_Core_StartService,
      callback);
};


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.startService =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/StartService',
      request,
      metadata || {},
      methodDescriptor_Core_StartService);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.CoreInfoResponse>}
 */
const methodDescriptor_Core_Stop = new grpc.web.MethodDescriptor(
  '/hcore.Core/Stop',
  grpc.web.MethodType.UNARY,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.CoreInfoResponse,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.stop =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/Stop',
      request,
      metadata || {},
      methodDescriptor_Core_Stop,
      callback);
};


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.stop =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/Stop',
      request,
      metadata || {},
      methodDescriptor_Core_Stop);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.StartRequest,
 *   !proto.hcore.CoreInfoResponse>}
 */
const methodDescriptor_Core_Restart = new grpc.web.MethodDescriptor(
  '/hcore.Core/Restart',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.StartRequest,
  v2_hcore_hcore_pb.CoreInfoResponse,
  /**
   * @param {!proto.hcore.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.restart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/Restart',
      request,
      metadata || {},
      methodDescriptor_Core_Restart,
      callback);
};


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.restart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/Restart',
      request,
      metadata || {},
      methodDescriptor_Core_Restart);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.StartRequest,
 *   !proto.hcore.CoreInfoResponse>}
 */
const methodDescriptor_Core_HotReload = new grpc.web.MethodDescriptor(
  '/hcore.Core/HotReload',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.StartRequest,
  v2_hcore_hcore_pb.CoreInfoResponse,
  /**
   * @param {!proto.hcore.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.hotReload =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/HotReload',
      request,
      metadata || {},
      methodDescriptor_Core_HotReload,
      callback);
};


/**
 * @param {!proto.hcore.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.hotReload =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/HotReload',
      request,
      metadata || {},
      methodDescriptor_Core_HotReload);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.SelectOutboundRequest,
 *   !proto.hcommon.Response>}
 */
const methodDescriptor_Core_SelectOutbound = new grpc.web.MethodDescriptor(
  '/hcore.Core/SelectOutbound',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.SelectOutboundRequest,
  v2_hcommon_common_pb.Response,
  /**
   * @param {!proto.hcore.SelectOutboundRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcommon_common_pb.Response.deserializeBinary
);


/**
 * @param {!proto.hcore.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcommon.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcommon.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.selectOutbound =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/SelectOutbound',
      request,
      metadata || {},
      methodDescriptor_Core_SelectOutbound,
      callback);
};


/**
 * @param {!proto.hcore.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcommon.Response>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.selectOutbound =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/SelectOutbound',
      request,
      metadata || {},
      methodDescriptor_Core_SelectOutbound);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.UrlTestRequest,
 *   !proto.hcommon.Response>}
 */
const methodDescriptor_Core_UrlTest = new grpc.web.MethodDescriptor(
  '/hcore.Core/UrlTest',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.UrlTestRequest,
  v2_hcommon_common_pb.Response,
  /**
   * @param {!proto.hcore.UrlTestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcommon_common_pb.Response.deserializeBinary
);


/**
 * @param {!proto.hcore.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcommon.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcommon.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.urlTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/UrlTest',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTest,
      callback);
};


/**
 * @param {!proto.hcore.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcommon.Response>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.urlTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/UrlTest',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcommon.Response>}
 */
const methodDescriptor_Core_UrlTestActive = new grpc.web.MethodDescriptor(
  '/hcore.Core/UrlTestActive',
  grpc.web.MethodType.UNARY,
  v2_hcommon_common_pb.Empty,
  v2_hcommon_common_pb.Response,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcommon_common_pb.Response.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcommon.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcommon.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.urlTestActive =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/UrlTestActive',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTestActive,
      callback);
};


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcommon.Response>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.urlTestActive =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/UrlTestActive',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTestActive);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.GenerateWarpConfigRequest,
 *   !proto.hcore.WarpGenerationResponse>}
 */
const methodDescriptor_Core_GenerateWarpConfig = new grpc.web.MethodDescriptor(
  '/hcore.Core/GenerateWarpConfig',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.GenerateWarpConfigRequest,
  v2_hcore_hcore_pb.WarpGenerationResponse,
  /**
   * @param {!proto.hcore.GenerateWarpConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.WarpGenerationResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.WarpGenerationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.WarpGenerationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.generateWarpConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/GenerateWarpConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateWarpConfig,
      callback);
};


/**
 * @param {!proto.hcore.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.WarpGenerationResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.generateWarpConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/GenerateWarpConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateWarpConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.SystemProxyStatus>}
 */
const methodDescriptor_Core_GetSystemProxyStatus = new grpc.web.MethodDescriptor(
  '/hcore.Core/GetSystemProxyStatus',
  grpc.web.MethodType.UNARY,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.SystemProxyStatus,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.SystemProxyStatus.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.SystemProxyStatus)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.SystemProxyStatus>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.getSystemProxyStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/GetSystemProxyStatus',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus,
      callback);
};


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.SystemProxyStatus>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.getSystemProxyStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/GetSystemProxyStatus',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.SetSystemProxyEnabledRequest,
 *   !proto.hcommon.Response>}
 */
const methodDescriptor_Core_SetSystemProxyEnabled = new grpc.web.MethodDescriptor(
  '/hcore.Core/SetSystemProxyEnabled',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.SetSystemProxyEnabledRequest,
  v2_hcommon_common_pb.Response,
  /**
   * @param {!proto.hcore.SetSystemProxyEnabledRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcommon_common_pb.Response.deserializeBinary
);


/**
 * @param {!proto.hcore.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcommon.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcommon.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.setSystemProxyEnabled =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/SetSystemProxyEnabled',
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled,
      callback);
};


/**
 * @param {!proto.hcore.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcommon.Response>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.setSystemProxyEnabled =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/SetSystemProxyEnabled',
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.LogRequest,
 *   !proto.hcore.LogMessage>}
 */
const methodDescriptor_Core_LogListener = new grpc.web.MethodDescriptor(
  '/hcore.Core/LogListener',
  grpc.web.MethodType.SERVER_STREAMING,
  v2_hcore_hcore_pb.LogRequest,
  v2_hcore_hcore_pb.LogMessage,
  /**
   * @param {!proto.hcore.LogRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.LogMessage.deserializeBinary
);


/**
 * @param {!proto.hcore.LogRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.logListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/LogListener',
      request,
      metadata || {},
      methodDescriptor_Core_LogListener);
};


/**
 * @param {!proto.hcore.LogRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.hcore.CorePromiseClient.prototype.logListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/hcore.Core/LogListener',
      request,
      metadata || {},
      methodDescriptor_Core_LogListener);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.CloseRequest,
 *   !proto.hcommon.Empty>}
 */
const methodDescriptor_Core_Close = new grpc.web.MethodDescriptor(
  '/hcore.Core/Close',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.CloseRequest,
  v2_hcommon_common_pb.Empty,
  /**
   * @param {!proto.hcore.CloseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcommon_common_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.hcore.CloseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcommon.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcommon.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.close =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/Close',
      request,
      metadata || {},
      methodDescriptor_Core_Close,
      callback);
};


/**
 * @param {!proto.hcore.CloseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcommon.Empty>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.close =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/Close',
      request,
      metadata || {},
      methodDescriptor_Core_Close);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcore.NetworkProbeRequest,
 *   !proto.hcore.NetworkProbeResponse>}
 */
const methodDescriptor_Core_ProbeConnection = new grpc.web.MethodDescriptor(
  '/hcore.Core/ProbeConnection',
  grpc.web.MethodType.UNARY,
  v2_hcore_hcore_pb.NetworkProbeRequest,
  v2_hcore_hcore_pb.NetworkProbeResponse,
  /**
   * @param {!proto.hcore.NetworkProbeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.NetworkProbeResponse.deserializeBinary
);


/**
 * @param {!proto.hcore.NetworkProbeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.NetworkProbeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.NetworkProbeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.probeConnection =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/ProbeConnection',
      request,
      metadata || {},
      methodDescriptor_Core_ProbeConnection,
      callback);
};


/**
 * @param {!proto.hcore.NetworkProbeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.NetworkProbeResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.probeConnection =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/ProbeConnection',
      request,
      metadata || {},
      methodDescriptor_Core_ProbeConnection);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.IpInfo>}
 */
const methodDescriptor_Core_GetCurrentIpInfo = new grpc.web.MethodDescriptor(
  '/hcore.Core/GetCurrentIpInfo',
  grpc.web.MethodType.UNARY,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.IpInfo,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.IpInfo.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.IpInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.IpInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.getCurrentIpInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/GetCurrentIpInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetCurrentIpInfo,
      callback);
};


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.IpInfo>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.getCurrentIpInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/GetCurrentIpInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetCurrentIpInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.hcommon.Empty,
 *   !proto.hcore.LANIPResponse>}
 */
const methodDescriptor_Core_GetLANIP = new grpc.web.MethodDescriptor(
  '/hcore.Core/GetLANIP',
  grpc.web.MethodType.UNARY,
  v2_hcommon_common_pb.Empty,
  v2_hcore_hcore_pb.LANIPResponse,
  /**
   * @param {!proto.hcommon.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  v2_hcore_hcore_pb.LANIPResponse.deserializeBinary
);


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.hcore.LANIPResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.hcore.LANIPResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.hcore.CoreClient.prototype.getLANIP =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/hcore.Core/GetLANIP',
      request,
      metadata || {},
      methodDescriptor_Core_GetLANIP,
      callback);
};


/**
 * @param {!proto.hcommon.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.hcore.LANIPResponse>}
 *     Promise that resolves to the response
 */
proto.hcore.CorePromiseClient.prototype.getLANIP =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/hcore.Core/GetLANIP',
      request,
      metadata || {},
      methodDescriptor_Core_GetLANIP);
};


module.exports = proto.hcore;
